import { Octokit } from "@octokit/rest";
import { logger } from "./logger";
import { secretsDb } from "./secrets";

export interface SyncFile {
  filePath: string;
  content: string;
}

/** Returns true if a GitHub PAT is stored. */
export function hasGitHubPat(): boolean {
  return secretsDb.getGitHubPat() !== null;
}

/**
 * Create a new GitHub repository and push all files as a single commit.
 * If the repo already exists (422), pushes a new commit on top of the current HEAD.
 */
export async function createRepoAndPush(
  repoName: string,
  files: SyncFile[]
): Promise<string> {
  const pat = secretsDb.getGitHubPat();
  if (!pat) {
    throw new Error("No GitHub token configured. Please add a Personal Access Token in the API Keys page.");
  }

  const octokit = new Octokit({ auth: pat });

  const { data: ghUser } = await octokit.rest.users.getAuthenticated();
  const owner = ghUser.login;
  logger.info({ owner, repoName }, "Starting GitHub sync");

  // ── Step 1: create repo or fetch existing one ─────────────────────────────
  let repoHtmlUrl: string;
  let existingHeadSha: string | null = null;
  let existingTreeSha: string | null = null;

  try {
    const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
      name: repoName,
      private: false,
      auto_init: false,
      description: "Generated by Woxsom Code",
    });
    repoHtmlUrl = repo.html_url;
    logger.info({ owner, repoName, url: repoHtmlUrl }, "New repository created");
  } catch (err: unknown) {
    const status = (err as { status?: number }).status;
    if (status === 422) {
      // Repo already exists — fetch its current HEAD so we can push on top
      logger.info({ owner, repoName }, "Repository already exists, pushing update commit");
      const { data: existingRepo } = await octokit.rest.repos.get({ owner, repo: repoName });
      repoHtmlUrl = existingRepo.html_url;
      const defaultBranch = existingRepo.default_branch;

      try {
        const { data: ref } = await octokit.rest.git.getRef({
          owner,
          repo: repoName,
          ref: `heads/${defaultBranch}`,
        });
        existingHeadSha = ref.object.sha;
        const { data: headCommit } = await octokit.rest.git.getCommit({
          owner,
          repo: repoName,
          commit_sha: existingHeadSha,
        });
        existingTreeSha = headCommit.tree.sha;
      } catch {
        // Repo exists but is empty — treat as fresh
      }
    } else {
      throw err;
    }
  }

  // ── Step 2: create blobs in batches of 5 ─────────────────────────────────
  const batchSize = 5;
  const treeEntries: Array<{ path: string; mode: "100644"; type: "blob"; sha: string }> = [];

  for (let i = 0; i < files.length; i += batchSize) {
    const batch = files.slice(i, i + batchSize);
    const blobs = await Promise.all(
      batch.map((f) =>
        octokit.rest.git.createBlob({
          owner,
          repo: repoName,
          content: Buffer.from(f.content, "utf8").toString("base64"),
          encoding: "base64",
        })
      )
    );
    blobs.forEach((blob, idx) => {
      treeEntries.push({ path: batch[idx].filePath, mode: "100644", type: "blob", sha: blob.data.sha });
    });
    logger.info({ owner, repoName, batchIndex: Math.floor(i / batchSize) + 1 }, "Blob batch created");
  }

  // ── Step 3: create Git tree ───────────────────────────────────────────────
  const { data: tree } = await octokit.rest.git.createTree({
    owner,
    repo: repoName,
    tree: treeEntries,
    ...(existingTreeSha ? { base_tree: existingTreeSha } : {}),
  });

  // ── Step 4: create commit ─────────────────────────────────────────────────
  const { data: commit } = await octokit.rest.git.createCommit({
    owner,
    repo: repoName,
    message: existingHeadSha
      ? "Update — regenerated by Woxsom Code"
      : "Initial commit — generated by Woxsom Code",
    tree: tree.sha,
    parents: existingHeadSha ? [existingHeadSha] : [],
  });

  // ── Step 5: create or update the main branch ref ─────────────────────────
  if (existingHeadSha) {
    await octokit.rest.git.updateRef({
      owner, repo: repoName, ref: "heads/main", sha: commit.sha, force: false,
    });
  } else {
    await octokit.rest.git.createRef({
      owner, repo: repoName, ref: "refs/heads/main", sha: commit.sha,
    });
  }

  logger.info({ owner, repoName, fileCount: treeEntries.length, url: repoHtmlUrl }, "GitHub sync complete");
  return repoHtmlUrl;
}
