import { createAppAuth } from "@octokit/auth-app";
import { Octokit } from "@octokit/rest";
import { logger } from "./logger";

// ─── In-memory token store: sessionId → GitHub user access token ─────────────
// Sufficient for an internal single-server tool. Does not persist across restarts.
const userTokens = new Map<string, string>();

function getAppCredentials() {
  const appId = process.env.GITHUB_APP_ID;
  const privateKey = (process.env.GITHUB_PRIVATE_KEY ?? "").replace(/\\n/g, "\n");
  const clientId = process.env.GITHUB_CLIENT_ID;
  const clientSecret = process.env.GITHUB_CLIENT_SECRET;

  if (!appId || !privateKey || !clientId || !clientSecret) {
    throw new Error(
      "GitHub App credentials are not fully configured. Set GITHUB_APP_ID, GITHUB_PRIVATE_KEY, GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET."
    );
  }
  return { appId, privateKey, clientId, clientSecret };
}

/** Build the GitHub OAuth authorization URL. state = sessionId so we can route back. */
export function getOAuthUrl(state: string): string {
  const { clientId } = getAppCredentials();
  const params = new URLSearchParams({
    client_id: clientId,
    state,
    scope: "repo",
  });
  return `https://github.com/login/oauth/authorize?${params.toString()}`;
}

/** Exchange the OAuth code for a user access token and store it against the sessionId. */
export async function exchangeCodeAndStore(code: string, sessionId: string): Promise<void> {
  const creds = getAppCredentials();
  const auth = createAppAuth({
    appId: creds.appId,
    privateKey: creds.privateKey,
    clientId: creds.clientId,
    clientSecret: creds.clientSecret,
  });

  const userAuth = await auth({ type: "oauth-user", code });
  userTokens.set(sessionId, (userAuth as { token: string }).token);
  logger.info({ sessionId }, "GitHub user access token stored");
}

/** Returns true if a user token is available for this session. */
export function hasGitHubToken(sessionId: string): boolean {
  return userTokens.has(sessionId);
}

/** Remove the stored token for a session. */
export function clearGitHubToken(sessionId: string): void {
  userTokens.delete(sessionId);
}

export interface SyncFile {
  filePath: string;
  content: string;
}

/**
 * Create a new GitHub repository and push all files in a single initial commit.
 * Uses the stored user access token for the given sessionId.
 */
export async function createRepoAndPush(
  sessionId: string,
  repoName: string,
  files: SyncFile[]
): Promise<string> {
  const token = userTokens.get(sessionId);
  if (!token) {
    throw new Error("No GitHub token for this session. Please connect GitHub first.");
  }

  const octokit = new Octokit({ auth: token });

  // 1. Get the authenticated user's login
  const { data: ghUser } = await octokit.rest.users.getAuthenticated();
  const owner = ghUser.login;
  logger.info({ owner, repoName }, "Creating GitHub repository");

  // 2. Create the repository (empty, no auto-init — we'll push the initial commit)
  let repoHtmlUrl: string;
  try {
    const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
      name: repoName,
      private: false,
      auto_init: false,
      description: "Generated by Woxsom Code",
    });
    repoHtmlUrl = repo.html_url;
  } catch (err: unknown) {
    const status = (err as { status?: number }).status;
    if (status === 422) {
      throw new Error(`Repository "${repoName}" already exists on your GitHub account.`);
    }
    throw err;
  }

  // 3. Create blobs for every file (in parallel batches of 5 to avoid rate limits)
  const batchSize = 5;
  const treeEntries: Array<{
    path: string;
    mode: "100644";
    type: "blob";
    sha: string;
  }> = [];

  for (let i = 0; i < files.length; i += batchSize) {
    const batch = files.slice(i, i + batchSize);
    const blobs = await Promise.all(
      batch.map((f) =>
        octokit.rest.git.createBlob({
          owner,
          repo: repoName,
          content: Buffer.from(f.content, "utf8").toString("base64"),
          encoding: "base64",
        })
      )
    );
    blobs.forEach((blob, idx) => {
      treeEntries.push({
        path: batch[idx].filePath,
        mode: "100644",
        type: "blob",
        sha: blob.data.sha,
      });
    });
    logger.info({ owner, repoName, batch: i / batchSize + 1 }, "Blob batch created");
  }

  // 4. Create the Git tree
  const { data: tree } = await octokit.rest.git.createTree({
    owner,
    repo: repoName,
    tree: treeEntries,
  });

  // 5. Create the initial commit (no parents — empty repo)
  const { data: commit } = await octokit.rest.git.createCommit({
    owner,
    repo: repoName,
    message: "Initial commit — generated by Woxsom Code",
    tree: tree.sha,
    parents: [],
  });

  // 6. Create the main branch reference
  await octokit.rest.git.createRef({
    owner,
    repo: repoName,
    ref: "refs/heads/main",
    sha: commit.sha,
  });

  logger.info({ owner, repoName, files: treeEntries.length, url: repoHtmlUrl }, "GitHub sync complete");
  return repoHtmlUrl;
}
