import { Octokit } from "@octokit/rest";
import { logger } from "./logger";
import { secretsDb } from "./secrets";

export interface SyncFile {
  filePath: string;
  content: string;
}

/** Returns true if a GitHub PAT is stored. */
export function hasGitHubPat(): boolean {
  return secretsDb.getGitHubPat() !== null;
}

/**
 * Resolves the current HEAD sha and tree sha of the default branch.
 * Returns nulls if the repo has no commits yet (should not happen with auto_init,
 * but handled defensively).
 */
async function resolveHead(
  octokit: Octokit,
  owner: string,
  repo: string,
  defaultBranch: string
): Promise<{ headSha: string; treeSha: string } | null> {
  try {
    const { data: ref } = await octokit.rest.git.getRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
    });
    const headSha = ref.object.sha;
    const { data: commit } = await octokit.rest.git.getCommit({
      owner,
      repo,
      commit_sha: headSha,
    });
    return { headSha, treeSha: commit.tree.sha };
  } catch {
    // Repo exists but is genuinely empty (no commits) — should not happen
    // with auto_init:true, but we handle it defensively.
    return null;
  }
}

/**
 * Create or update a GitHub repository and push all project files.
 * - New repo: created with auto_init:true (GitHub makes an initial commit),
 *   then a second commit with all project files is pushed on top.
 * - Existing repo (422): project files are pushed as a new commit on top of HEAD.
 */
export async function createRepoAndPush(
  repoName: string,
  files: SyncFile[]
): Promise<string> {
  const pat = secretsDb.getGitHubPat();
  if (!pat) {
    throw new Error(
      "No GitHub token configured. Please add a Personal Access Token in the API Keys page."
    );
  }

  const octokit = new Octokit({ auth: pat });

  const { data: ghUser } = await octokit.rest.users.getAuthenticated();
  const owner = ghUser.login;
  logger.info({ owner, repoName }, "Starting GitHub sync");

  // ── Step 1: ensure the repository exists and is initialised ──────────────
  let repoHtmlUrl: string;
  let defaultBranch: string;

  try {
    // auto_init:true → GitHub creates an initial commit so the git backend
    // is always ready for subsequent API calls. No more 409 "empty repo".
    const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
      name: repoName,
      private: false,
      auto_init: true,
      description: "Generated by Woxsom Code",
    });
    repoHtmlUrl = repo.html_url;
    defaultBranch = repo.default_branch;
    logger.info({ owner, repoName, url: repoHtmlUrl }, "New repository created");
  } catch (err: unknown) {
    const status = (err as { status?: number }).status;
    if (status === 422) {
      // Repo already exists — that's fine, we'll push on top of its HEAD
      const { data: existingRepo } = await octokit.rest.repos.get({ owner, repo: repoName });
      repoHtmlUrl = existingRepo.html_url;
      defaultBranch = existingRepo.default_branch;
      logger.info({ owner, repoName }, "Repository already exists, pushing update commit");
    } else {
      throw err;
    }
  }

  // ── Step 2: get current HEAD (always present because of auto_init) ────────
  const head = await resolveHead(octokit, owner, repoName, defaultBranch);
  // head can only be null if someone deleted all commits after creation;
  // in that edge case we push an orphan commit (parents: []).

  // ── Step 3: create blobs in batches of 5 ─────────────────────────────────
  const batchSize = 5;
  const treeEntries: Array<{
    path: string;
    mode: "100644";
    type: "blob";
    sha: string;
  }> = [];

  for (let i = 0; i < files.length; i += batchSize) {
    const batch = files.slice(i, i + batchSize);
    const blobs = await Promise.all(
      batch.map((f) =>
        octokit.rest.git.createBlob({
          owner,
          repo: repoName,
          content: Buffer.from(f.content, "utf8").toString("base64"),
          encoding: "base64",
        })
      )
    );
    blobs.forEach((blob, idx) => {
      treeEntries.push({
        path: batch[idx].filePath,
        mode: "100644",
        type: "blob",
        sha: blob.data.sha,
      });
    });
    logger.info(
      { owner, repoName, batchIndex: Math.floor(i / batchSize) + 1 },
      "Blob batch created"
    );
  }

  // ── Step 4: create Git tree (layered on top of existing tree if present) ──
  const { data: tree } = await octokit.rest.git.createTree({
    owner,
    repo: repoName,
    tree: treeEntries,
    ...(head ? { base_tree: head.treeSha } : {}),
  });

  // ── Step 5: create commit ─────────────────────────────────────────────────
  const { data: commit } = await octokit.rest.git.createCommit({
    owner,
    repo: repoName,
    message: head
      ? "Update — regenerated by Woxsom Code"
      : "Initial commit — generated by Woxsom Code",
    tree: tree.sha,
    parents: head ? [head.headSha] : [],
  });

  // ── Step 6: update the default branch to point at the new commit ──────────
  await octokit.rest.git.updateRef({
    owner,
    repo: repoName,
    ref: `heads/${defaultBranch}`,
    sha: commit.sha,
    force: false,
  });

  logger.info(
    { owner, repoName, fileCount: treeEntries.length, url: repoHtmlUrl },
    "GitHub sync complete"
  );
  return repoHtmlUrl;
}
